# Generated by Django 5.0.3 on 2024-04-21 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_description_task_limit_date_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In Progress", "Progress"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=100,
            ),
        ),
    ]
